name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js '10.x'
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm run build
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs'
          branch: main
          message: 'Built latest static version'
